### ISSUE TITLE
初步开发计划图 (Initial Development Project Roadmap)

### ISSUE THREAD

**Issue by Steve-xmh** [Steve-xmh/amll-ttml-tool#2]
- [x] 基本功能
  - [x] 基本输入、编辑、打轴功能
  - [x] 读取保存 TTML 格式歌词
  - [x] 配置歌词行行为（背景歌词、对唱歌词等）
  - [x] 配置歌词文件元数据（名称，作者，网易云音乐ID等）
  - [x] 拆分单词
  - [x] 组合单词
  - [x] 移动单词
- [x] 高级功能
  - [x] LRC/YRC/QRC 歌词文件的导入导出
  - [x] 通过纯文本导入歌词（可选自定助记符以自动拆分单词）
  - [x] Lyricify Syllable 歌词文件的导入导出
  - ~~基于 Lyricify Syllable 格式的纯文本编辑模式（由于未来扩展TTML内容的缘故取消计划）~~
  - [x] Jieba 分词拆分句子
  - [x] 无 CJK 下的简单拆分句子
  - ~~[ ] 打轴模式按键速查表（推迟制作）~~
  - [x] 对日语下的汉字启用注音标注
  - [x] ASS 字幕文件的导出（酌情实现导入）
  - [x] AMLL 歌词效果预览
  - ~~生成网易云形式的日语音译歌词行（由于生成准确度因素取消计划）~~
  - ~~生成网易云格式的粤语音译歌词行（由于生成准确度因素取消计划）~~
  - [x] 可配置的快捷键
  - ~~从 Apple Music 中获取 Apple Syllable 逐词歌词（也是 TTML 歌词）（推迟制作）~~
  - ~~移动端布局操作支持（推迟制作）~~
  - [x] 国际化（Internationalization）支持

如有其他功能建议欢迎在下面回复！

**Comment by kengwang** [comment]
对于日语歌词, 提示将每个字提示其罗马字

**Comment by mizuhara37** [comment]
打轴模式时，如果上方显示的那行歌词较长，在进行打轴时需要边移动滚动条边打轴，有点麻烦，希望能让待打轴单词能一直显示在显示范围内🫡

**Comment by tsavpyn** [comment]
1. **增加对于俄语歌词的转写支持（类似日语罗马音）**
2. **点击字块时时间轴跳转到对应的位置**
3. **“编辑模式”下 Lyricify Syllable 歌词 切换视图：分词，合并，自由编辑（纯文本编辑）**
4. **增加“按空格分词”，以增加对俄语和其他语言歌词的分词支持**
5. **更清晰的“背景人声歌词”“对唱歌词 左”“对唱歌词 右”按钮（参考Lyricify歌词管理器）**
6. 切换字体样式，颜色
7. **自定义快捷键**
8. 更适合的西文“打轴模式”视图（另说明）
9. 更强的兼容性（例如自动屏蔽metadata歌词而不会直接runtime error）
10. 真正的桌面端（支持“项目”和“保存”）（另说明）

**Comment by mcuTiger** [comment]
通过纯文本来导入歌词

**Comment by Sinofine** [comment]
Dear,
I've made a lyric service which get precise lyrics from kugou/qq/163 recently. After I see you made this project, I made my service support ttml. Hope it may help you.

source: https://github.com/Copay/CaraokeHost

---

examples of my service:
https://caraoke.sinofine.me/api/kugou/%E3%82%A2%E3%83%87%E3%82%A3%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%AB%E3%83%A1%E3%83%A2%E3%83%AA%E3%83%BC?format=ttml
https://caraoke.sinofine.me/api/qq/%E3%82%A2%E3%83%87%E3%82%A3%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%AB%E3%83%A1%E3%83%A2%E3%83%AA%E3%83%BC?format=ttml
https://caraoke.sinofine.me/api/163/%E3%82%A2%E3%83%87%E3%82%A3%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%AB%E3%83%A1%E3%83%A2%E3%83%AA%E3%83%BC?format=ttml
https://caraoke.sinofine.me/api/qq/id/218845692?format=ttml
https://caraoke.sinofine.me/api/163/id/1321543977?format=ttml
https://caraoke.sinofine.me/api/kugou/id/3d9926262953bc8f7956e2c6f3a7458f?format=ttml

**Comment by Sinofine** [comment]
Furthermore, I think [CaraokeHost](https://github.com/Copay/CaraokeHost) should be easy to be integrated in applemusic-like-lyrics.

**Comment by Steve-xmh** [comment]
> Furthermore, I think [CaraokeHost](https://github.com/Copay/CaraokeHost) should be easy to be integrated in applemusic-like-lyrics as they are both written in javascript.

非常好的歌词源后端！我能明白大佬想要将这个歌词源推荐给我。之后会考虑在编辑器内加入对大佬的歌词源功能的检索导入功能。

如果你还希望将歌词源嵌入到插件本体的话，插件本体的开发版本现在已经支持自定义歌词源功能，你可以通过插件内歌词源功能添加你的歌词源，然后右键分享歌词源字符串，即可让大家使用任何一方的歌词了。所以我想之后可以在插件的 README 上推荐使用来自你们的歌词源，这样就能让逐字歌词有更多的来源可以取用了！

例如以大佬的 `https://caraoke.sinofine.me/api/kugou/%E3%82%A2%E3%83%87%E3%82%A3%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%AB%E3%83%A1%E3%83%A2%E3%83%AA%E3%83%BC?format=ttml` 为例，中间的歌名部分通过使用 `[SONG_NAME_URI]` 来替代，模板字符串就是： `https://caraoke.sinofine.me/api/kugou/[SONG_NAME_URI]?format=ttml`。

<img width="578" alt="image" src="https://github.com/Steve-xmh/amll-ttml-tool/assets/39523898/f9c8b42f-6f95-4a5d-86f7-13f9a669e7f4">

在右键新加入的歌词源项目中即可右键复制出歌词源字符串：

<img width="371" alt="image" src="https://github.com/Steve-xmh/amll-ttml-tool/assets/39523898/aa53beb3-ee64-4afd-8f51-9009a14649bd">

另外有两个需要提醒的，链接需要返回歌词文件原始数据，而不是其他格式，且如果找不到歌词等情况需要以 4XX 响应返回，以让 AMLL 继续查询其他歌词源，然后使用TTML歌词是为了让歌词能够获得更多演出效果（例如嵌入翻译音译、对唱视图和背景人声），如果只是单纯的将逐字歌词转换成了TTML格式的话就没有意义了。毕竟AMLL能支持读写几乎大部分歌词格式（LRC,YRC,QRC(含加密),TTML,Lyricify Syllable）。

具体可以参考源代码 https://github.com/Steve-xmh/applemusic-like-lyrics/blob/1a40c338dc44944bf7674685cfa45e7691434090/packages/bncm/src/lyric/source.ts#L24-L85

<img width="1582" alt="image" src="https://github.com/Steve-xmh/amll-ttml-tool/assets/39523898/a6ebee7b-ceca-492b-acc2-58bc5a45b597">

**Comment by MianSoft** [comment]
## 更多快捷键
1. 保存相关快捷键, 如 `Ctrl+S`
2. 定位到目标单词的开始时间 `T` / 结束时间 `U` ( 与 R 和 Y 对应 )
3. 更细致的时间定位, 默认 ⬅➡ 应该是向前 / 向后一秒, 按住 `Ctrl` 时才是向前 / 向后五秒

**Comment by PlumPlum-FISH** [comment]
希望能增加：背景人声歌词的结束时间与上一句主歌词句子结束时间对齐的功能，有时候手动比较难调（如果左右两边时轴能直接左键修改的话也行🧐

**Comment by Miaoyww** [comment]
语言切换。当语言识别有问题时会很有帮助…

**Comment by ranhengzhang** [comment]
> 希望能有 ASS 字幕完整（ 卡拉OK、说话人等 ）导入导出。

@ShuiHuo 我写了份Aegisub自动化脚本和一份字幕模板，可以用于将ass字幕单向转为TTML，希望对你有帮助：

[ass2ttml.lua](https://github.com/ranhengzhang/amll-ttml-db-raw-data/blob/main/ass2ttml.lua)

[ass2ttml.ass](https://github.com/ranhengzhang/amll-ttml-db-raw-data/blob/main/ass2ttml.ass)
